global:
    ssh_key: ~/.ssh/id_rsa # Will use this by default if nothing else is specified
    ssh_key_password: id_rsa_pwd # Selects a credential from credentials-file.
    ssh_password: password # Password can also be specified instead of ssh
    credentials_file: ~/dbman-credentials # encrypted file
    editor: nvim

    # Tunnels can be specified on global level, or on specific connections.
    tunnels:
      - target: 10.0.1.15
        host: 10.0.1.4
        ssh_key: ~/.ssh/id_rsa
        ssh_key_password: id_rsa_pwd # Selects a credential from credentials-file.
        jumphost: 10.0.1.5 
        jumphost_ssh_key: ~/.ssh/id_rsa
        jumphost_ssh_key_password: id_rsa_pwd # Selects a credential from credentials-file.
        ssh_password: password # Can also specify password instead of SSH
      - target: 10.0.1.16
        cmd: "ssh -i ~/.ssh/id_rsa -L 127.0.0.1:3306:10.0.1.16:3306" # Optionally, the SSH command can simply be specified directly.

connections:
    - name: prod-db
      group: prod
      client: mysqlsh
      host: 10.0.1.15
      port: 3306
      cmd_opts: "--sslmode=require"
      credentials: prod-app-user # Selects a credential from credentials-file.
      read_only: false
      tunnel:
          host: 10.0.1.4
          ssh_key: ~/.ssh/id_rsa
          ssh_key_password: id_rsa_pwd # Selects a credential from credentials-file.
          jumphost: 10.0.1.5 
          jumphost_ssh_key: ~/.ssh/id_rsa
          jumphost_ssh_key_password: id_rsa_pwd # Selects a credential from credentials-file.
          ssh_password: password # Can also specify password instead of SSH
          cmd_opts: something # custom cmd opts can also be specified to the SSH command

    # Connections can be "inherited" to select specific DBs or override certain fields
    - name: prod-db-app
      base: prod-db
      db: myapp 

    - name: prod-db-app-select-items
      base: prod-db
      db: myapp 
      exec: "select * from items;" # A connection can also be made to execute a command

    - name: local-test
      cmd: "mysql -h 0.0.0.0 -u test -p" # It's also possible to simply specify a cli command that this connection will run when triggered.
      tunnel: 

